import json

def make_cell(source_lines, cell_type="code"):
    return {
        "cell_type": cell_type,
        "metadata": {},
        "source": [line + "\n" for line in source_lines]
    }

step1_source = [
    "#@title Configuracion del Repositorio",
    "REPO_URL = \"https://github.com/Marco-Ravanello/Desarrollo.git\" #@param {type:\"string\"}",
    "BRANCH = \"fix/ocr-field-detection-enhancement-12094009015913255245\" #@param {type:\"string\"}",
    "GITHUB_TOKEN = \"\" #@param {type:\"string\"}",
    "",
    "import os",
    "import subprocess",
    "import shutil",
    "import time",
    "import socket",
    "import re",
    "",
    "target_dir = \"/content/MuniGestio\"",
    "",
    "def wait_for_port(port, host=\"127.0.0.1\", timeout=30.0):",
    "    start_time = time.time()",
    "    while True:",
    "        try:",
    "            with socket.create_connection((host, port), timeout=1):",
    "                return True",
    "        except (socket.timeout, ConnectionRefusedError):",
    "            time.sleep(1)",
    "            if time.time() - start_time > timeout:",
    "                return False",
    "",
    "print(\"📥 Instalando dependencias del sistema...\")",
    "subprocess.run([\"apt-get\", \"-y\", \"update\"], capture_output=True)",
    "subprocess.run([\"apt-get\", \"-y\", \"install\", \"postgresql\", \"postgresql-client\"], capture_output=True)",
    "subprocess.run([\"curl\", \"-L\", \"https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb\", \"-o\", \"cloudflared.deb\"], capture_output=True)",
    "subprocess.run([\"dpkg\", \"-i\", \"cloudflared.deb\"], capture_output=True)",
    "",
    "print(\"🐘 Iniciando PostgreSQL...\")",
    "os.system(\"service postgresql restart\")",
    "if not wait_for_port(5432):",
    "    print(\"❌ PostgreSQL no inició a tiempo.\")",
    "    raise Exception(\"Postgres failed to start\")",
    "",
    "print(\"👤 Configurando base de datos...\")",
    "os.system(\"sudo -u postgres psql -c \\\"SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'munidb' AND pid <> pg_backend_pid();\\\"\")",
    "os.system(\"sudo -u postgres psql -c \\\"DROP DATABASE IF EXISTS munidb;\\\"\")",
    "os.system(\"sudo -u postgres psql -c \\\"DROP USER IF EXISTS muniuser;\\\"\")",
    "os.system(\"sudo -u postgres psql -c \\\"CREATE USER muniuser WITH PASSWORD 'munipass';\\\"\")",
    "os.system(\"sudo -u postgres psql -c \\\"CREATE DATABASE munidb OWNER muniuser;\\\"\")",
    "os.system(\"sudo -u postgres psql -c \\\"ALTER USER muniuser WITH SUPERUSER;\\\"\")",
    "",
    "if os.path.exists(target_dir):",
    "    shutil.rmtree(target_dir)",
    "",
    "print(f\"📂 Clonando rama {BRANCH}...\")",
    "clone_url = REPO_URL.replace(\"https://\", f\"https://{GITHUB_TOKEN}@\") if GITHUB_TOKEN else REPO_URL",
    "my_env = os.environ.copy()",
    "my_env[\"GIT_TERMINAL_PROMPT\"] = \"0\"",
    "clone_cmd = f\"git clone -b {BRANCH} {clone_url} {target_dir}\"",
    "if os.system(clone_cmd) != 0:",
    "    print(f\"⚠️ Fallo al clonar rama {BRANCH}. Reintentando con rama por defecto...\")",
    "    if os.system(f\"git clone {clone_url} {target_dir}\") != 0:",
    "        print(\"❌ Error crítico: No se pudo clonar el repositorio.\")",
    "        raise Exception(\"Git clone failed\")",
    "",
    "if not os.path.exists(target_dir):",
    "    print(f\"❌ Error: El directorio {target_dir} no existe después del clonado.\")",
    "    raise Exception(\"Target directory not found\")",
    "",
    "os.chdir(target_dir)",
    "os.makedirs(\"public/uploads\", exist_ok=True)",
    "",
    "print(\"📦 Instalando dependencias de Node (con legacy-peer-deps)...\")",
    "if os.system(\"npm install --legacy-peer-deps\") != 0:",
    "    raise Exception(\"npm install failed\")",
    "",
    "with open(\".env\", \"w\") as f:",
    "    f.write(\"DATABASE_URL=\\\"postgresql://muniuser:munipass@127.0.0.1:5432/munidb?schema=public\\\"\\n\")",
    "    f.write(\"AUTH_SECRET=\\\"secret-key-for-colab-12345678\\\"\\n\")",
    "    f.write(\"AUTH_TRUST_HOST=\\\"true\\\"\\n\")",
    "",
    "print(\"🗄️ Sincronizando esquema de base de datos (Prisma v6)...\")",
    "if os.system(\"npx prisma db push\") != 0:",
    "    print(\"❌ Fallo en prisma db push. Reintentando con prisma@6...\")",
    "    if os.system(\"npx prisma@6 db push\") != 0:",
    "        raise Exception(\"Prisma sync failed\")",
    "",
    "print(\"🌱 Poblando datos iniciales...\")",
    "os.system(\"npx prisma db seed\")",
    "",
    "print(\"⚙️ Generando cliente Prisma...\")",
    "os.system(\"npx prisma generate\")",
    "print(\"✅ Configuración completada.\")"
]

step2_source = [
    "import os",
    "import time",
    "import subprocess",
    "import re",
    "from threading import Thread",
    "",
    "target_dir = \"/content/MuniGestio\"",
    "os.chdir(target_dir)",
    "",
    "print(\"📡 Iniciando túnel Cloudflare...\")",
    "cf_process = subprocess.Popen([\"cloudflared\", \"tunnel\", \"--url\", \"http://localhost:3000\"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)",
    "",
    "tunnel_url = \"\"",
    "print(\"⏳ Obteniendo URL pública...\")",
    "start_time = time.time()",
    "while time.time() - start_time < 60:",
    "    line = cf_process.stdout.readline()",
    "    if not line: break",
    "    if \"trycloudflare.com\" in line:",
    "        match = re.search(r\"https://[a-zA-Z0-9.-]+\\.trycloudflare\\.com\", line)",
    "        if match:",
    "            tunnel_url = match.group(0)",
    "            break",
    "    time.sleep(0.1)",
    "",
    "if not tunnel_url:",
    "    print(\"❌ No se pudo obtener la URL del túnel. Revisa los logs abajo.\")",
    "else:",
    "    print(f\"\\n🚀 URL PÚBLICA: {tunnel_url}\")",
    "    with open(\".env\", \"r\") as f: lines = f.readlines()",
    "    with open(\".env\", \"w\") as f:",
    "        for line in lines:",
    "            if not line.startswith(\"AUTH_URL=\") and not line.startswith(\"NEXTAUTH_URL=\"): f.write(line)",
    "        f.write(f\"AUTH_URL=\\\"{tunnel_url}\\\"\\n\")",
    "        f.write(f\"NEXTAUTH_URL=\\\"{tunnel_url}\\\"\\n\")",
    "",
    "print(\"🏗️ Compilando aplicación (esto puede tardar unos minutos)...\")",
    "print(\"📊 Estado de memoria antes del build:\")",
    "os.system(\"free -m\")",
    "",
    "# Sincronizar env vars para el proceso actual",
    "with open(\".env\", \"r\") as f:",
    "    for line in f:",
    "        if \"=\" in line:",
    "            key, val = line.strip().split(\"=\", 1)",
    "            os.environ[key] = val.strip('\"')",
    "",
    "# Ejecutamos el build capturando la salida para mostrarla solo si falla",
    "build_result = subprocess.run([\"npm\", \"run\", \"build\"], capture_output=True, text=True, env=os.environ)",
    "if build_result.returncode != 0:",
    "    print(\"❌ La compilación falló.\")",
    "    print(\"📝 LOG DE ERROR:\")",
    "    print(build_result.stdout)",
    "    print(build_result.stderr)",
    "    raise Exception(\"Build failed\")",
    "print(\"✅ Compilación exitosa.\")",
    "",
    "print(\"🚀 Iniciando servidor Next.js...\")",
    "def start_server():",
    "    process = subprocess.Popen(\"npm run start\", shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1, env=os.environ)",
    "    for line in process.stdout: print(f\"[Server] {line.strip()}\")",
    "Thread(target=start_server, daemon=True).start()",
    "",
    "try:",
    "    while True:",
    "        line = cf_process.stdout.readline()",
    "        if line: print(f\"[Cloudflare] {line.strip()}\")",
    "        else: time.sleep(1)",
    "except KeyboardInterrupt: pass"
]

notebook = {
    "cells": [
        make_cell(["# 🛠️ Paso 1: Configuración del Entorno", "", "Instala dependencias, configura la base de datos y clona el proyecto."], "markdown"),
        make_cell(step1_source),
        make_cell(["# 🚀 Paso 2: Iniciar Servidor y Túnel", "", "Ejecuta esta celda para obtener la URL pública y arrancar el sistema.", "", "### ⚠️ Importante:", "Copia la URL que termina en `.trycloudflare.com` y ábrela en tu navegador."], "markdown"),
        make_cell(step2_source)
    ],
    "metadata": {
        "kernelspec": { "display_name": "Python 3", "language": "python", "name": "python3" }
    },
    "nbformat": 4, "nbformat_minor": 4
}

with open("Plataforma_Municipal_Colab.ipynb", "w") as f:
    json.dump(notebook, f, indent=1)
