import json

def make_cell(source_lines, cell_type="code"):
    return {
        "cell_type": cell_type,
        "metadata": {},
        "source": [line + "\n" for line in source_lines]
    }

step1_source = [
    "#@title Configuracion del Repositorio",
    "REPO_URL = \"https://github.com/Marco-Ravanello/Desarrollo.git\" #@param {type:\"string\"}",
    "BRANCH = \"fix/colab-deployment-v11\" #@param {type:\"string\"}",
    "GITHUB_TOKEN = \"\" #@param {type:\"string\"}",
    "",
    "import os",
    "import subprocess",
    "import shutil",
    "import time",
    "import socket",
    "",
    "target_dir = \"/content/MuniGestio\"",
    "",
    "def wait_for_port(port, host=\"127.0.0.1\", timeout=30.0):",
    "    start_time = time.time()",
    "    while True:",
    "        try:",
    "            with socket.create_connection((host, port), timeout=1):",
    "                return True",
    "        except (socket.timeout, ConnectionRefusedError):",
    "            time.sleep(1)",
    "            if time.time() - start_time > timeout:",
    "                return False",
    "",
    "print(\"📥 Instalando PostgreSQL...\")",
    "subprocess.run([\"apt-get\", \"-y\", \"update\"], capture_output=True)",
    "subprocess.run([\"apt-get\", \"-y\", \"install\", \"postgresql\", \"postgresql-client\"], capture_output=True)",
    "",
    "print(\"🐘 Iniciando PostgreSQL...\")",
    "os.system(\"service postgresql restart\")",
    "if not wait_for_port(5432):",
    "    print(\"❌ PostgreSQL no inició a tiempo.\")",
    "    raise Exception(\"Postgres failed to start\")",
    "",
    "print(\"👤 Configurando base de datos...\")",
    "# Intentamos cerrar conexiones activas a la DB si existe",
    "os.system(\"sudo -u postgres psql -c \\\"SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'munidb' AND pid <> pg_backend_pid();\\\"\")",
    "os.system(\"sudo -u postgres psql -c \\\"DROP DATABASE IF EXISTS munidb;\\\"\")",
    "os.system(\"sudo -u postgres psql -c \\\"DROP USER IF EXISTS muniuser;\\\"\")",
    "os.system(\"sudo -u postgres psql -c \\\"CREATE USER muniuser WITH PASSWORD 'munipass';\\\"\")",
    "os.system(\"sudo -u postgres psql -c \\\"CREATE DATABASE munidb OWNER muniuser;\\\"\")",
    "os.system(\"sudo -u postgres psql -c \\\"ALTER USER muniuser WITH SUPERUSER;\\\"\")",
    "",
    "if os.path.exists(target_dir):",
    "    shutil.rmtree(target_dir)",
    "",
    "print(f\"📂 Clonando rama {BRANCH}...\")",
    "clone_url = REPO_URL.replace(\"https://\", f\"https://{GITHUB_TOKEN}@\") if GITHUB_TOKEN else REPO_URL",
    "my_env = os.environ.copy()",
    "my_env[\"GIT_TERMINAL_PROMPT\"] = \"0\"",
    "subprocess.run([\"git\", \"clone\", \"-b\", BRANCH, clone_url, target_dir], check=True, env=my_env)",
    "",
    "os.chdir(target_dir)",
    "",
    "print(\"📦 Instalando dependencias...\")",
    "subprocess.run([\"npm\", \"install\"], capture_output=True)",
    "subprocess.run([\"npm\", \"install\", \"-g\", \"localtunnel\"], capture_output=True)",
    "",
    "with open(\".env\", \"w\") as f:",
    "    f.write(\"DATABASE_URL=\\\"postgresql://muniuser:munipass@127.0.0.1:5432/munidb?schema=public\\\"\\n\")",
    "    f.write(\"AUTH_SECRET=\\\"secret-key-for-colab-12345678\\\"\\n\")",
    "    f.write(\"AUTH_TRUST_HOST=\\\"true\\\"\\n\")",
    "",
    "print(\"🗄️ Sincronizando esquema de base de datos...\")",
    "res = subprocess.run([\"npx\", \"prisma\", \"db\", \"push\"], capture_output=True, text=True)",
    "print(res.stdout)",
    "if res.returncode != 0:",
    "    print(f\"❌ Error en db push: {res.stderr}\")",
    "    raise Exception(\"Prisma sync failed\")",
    "",
    "print(\"🌱 Poblando datos iniciales...\")",
    "res = subprocess.run([\"npx\", \"prisma\", \"db\", \"seed\"], capture_output=True, text=True)",
    "print(res.stdout)",
    "",
    "subprocess.run([\"npx\", \"prisma\", \"generate\"], capture_output=True)",
    "print(\"✅ Configuración completada.\")"
]

step2_source = [
    "import urllib.request",
    "import os",
    "import time",
    "import subprocess",
    "from threading import Thread",
    "",
    "target_dir = \"/content/MuniGestio\"",
    "os.chdir(target_dir)",
    "",
    "public_ip = urllib.request.urlopen(\"https://ipv4.icanhazip.com\").read().decode(\"utf8\").strip()",
    "print(f\"🔑 Tu \\\"Tunnel Password\\\" es: {public_ip}\")",
    "",
    "print(\"📡 Obteniendo URL del túnel...\")",
    "tunnel_process = subprocess.Popen([\"lt\", \"--port\", \"3000\"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)",
    "tunnel_url = \"\"",
    "for line in tunnel_process.stdout:",
    "    if \"your url is:\" in line:",
    "        tunnel_url = line.split(\"your url is:\")[1].strip()",
    "        break",
    "",
    "print(f\"🔗 URL del Túnel: {tunnel_url}\")",
    "",
    "with open(\".env\", \"r\") as f: lines = f.readlines()",
    "with open(\".env\", \"w\") as f:",
    "    for line in lines:",
    "        if not line.startswith(\"AUTH_URL=\"): f.write(line)",
    "    f.write(f\"AUTH_URL=\\\"{tunnel_url}\\\"\\n\")",
    "",
    "print(\"🏗️ Compilando aplicación...\")",
    "subprocess.run([\"npm\", \"run\", \"build\"], capture_output=True, text=True, check=True)",
    "",
    "print(\"🚀 Iniciando servidor Next.js...\")",
    "def start_server():",
    "    process = subprocess.Popen(\"npm run start\", shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1)",
    "    for line in process.stdout: print(f\"[Server] {line.strip()}\")",
    "Thread(target=start_server, daemon=True).start()",
    "",
    "print(\"⏳ Esperando servidor...\")",
    "for i in range(30):",
    "    try:",
    "        urllib.request.urlopen(\"http://127.0.0.1:3000\")",
    "        print(\"✅ ¡Listo!\")",
    "        break",
    "    except: time.sleep(2)",
    "",
    "print(f\"\\n🔗 ABRE ESTE ENLACE: {tunnel_url}\")",
    "try:",
    "    while True: time.sleep(1)",
    "except KeyboardInterrupt: pass"
]

notebook = {
    "cells": [
        make_cell(["# 🛠️ Paso 1: Configuración del Entorno", "", "Configura los datos del repositorio y descarga las dependencias."], "markdown"),
        make_cell(step1_source),
        make_cell(["# 🚀 Paso 2: Iniciar Servidor e Acceder", "", "### ⚠️ Instrucciones de Acceso:", "", "1. Copia la dirección IP que aparece abajo (es tu **Tunnel Password**).", "2. Haz clic en el enlace que termina en `.loca.lt`.", "3. En la página que se abre, pega la IP y dale a **Click to Submit**.", "4. El sistema cargará el Login. Usa `admin@municipio.gob.ar` / `admin123`."], "markdown"),
        make_cell(step2_source)
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

with open("Plataforma_Municipal_Colab.ipynb", "w") as f:
    json.dump(notebook, f, indent=1)
